name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          curl -sL https://github.com/goreleaser/goreleaser/releases/latest/download/goreleaser_$(uname -s)_$(uname -m).tar.gz | tar xz -C /tmp
          /tmp/goreleaser release --clean --config .goreleaser.forgejo.yml
        env:
          GITHUB_TOKEN: ""
          GITEA_TOKEN: ${{ secrets.GIT_TOKEN }}
